import type { Note } from '@/types'

// Work Notes demo data based on the latest pre-regression snapshot
export const DEMO_WORK_NOTES: Note[] = [
  // Work type notes
  {
    id: '1',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace lamp in FOH position 3',
    description: 'HPL 575W burnt out during tech rehearsal',
    priority: 'high',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-16T09:30:00'),
    updatedAt: new Date('2024-01-16T09:30:00'),
    lightwrightItemId: 'LW001',
    channelNumbers: '101, 102',
    positionUnit: 'FOH-3 Units 1-2',
    sceneryNeeds: 'Need ladder access behind set piece',
  },
  {
    id: '2',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Hang additional side light positions',
    description: 'Install 4 new fixtures on SL boom',
    priority: 'medium',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-14T08:15:00'),
    updatedAt: new Date('2024-01-15T17:45:00'),
    lightwrightItemId: 'LW078',
    channelNumbers: '201-204',
    positionUnit: 'Deck Edge Units 9-6',
    sceneryNeeds: 'Coordinate with scenic for boom placement',
  },
  {
    id: '3',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair damaged yoke on Unit 47',
    description: 'Tilt mechanism sticking, needs cleaning',
    priority: 'low',
    status: 'cancelled',
    type: 'work',
    createdAt: new Date('2024-01-12T14:20:00'),
    updatedAt: new Date('2024-01-14T11:30:00'),
    lightwrightItemId: 'LW047',
  },
  // Focus type notes
  {
    id: '4',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Gel replacement for cyc lights',
    description: 'Change R80 to R83 for warmer tone in Act 2',
    priority: 'medium',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-13T16:00:00'),
    updatedAt: new Date('2024-01-15T10:20:00'),
    lightwrightItemId: 'LW045',
    channelNumbers: '301-310',
    positionUnit: 'Cyc Units 1-10',
    sceneryNeeds: 'Access behind cyc during intermission only',
  },
  {
    id: '5',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Refocus specials after set change',
    description: 'Platform height changed, need to adjust 8 fixtures',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-16T11:45:00'),
    updatedAt: new Date('2024-01-16T11:45:00'),
    channelNumbers: '121-126',
    positionUnit: 'Balcony Rail Specials 1-8',
    sceneryNeeds: 'Wait until platform is final height',
  },
  {
    id: '6',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Barn door adjustment on front wash',
    description: 'Clean up spill light hitting proscenium',
    priority: 'low',
    status: 'cancelled',
    type: 'focus',
    createdAt: new Date('2024-01-11T13:30:00'),
    updatedAt: new Date('2024-01-13T09:15:00'),
    lightwrightItemId: 'LW023',
  },
  // Paperwork type notes
  {
    id: '7',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Update hookup with circuit changes',
    description: 'Circuits 47-52 reassigned to new dimmers',
    priority: 'medium',
    status: 'todo',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T14:30:00'),
    updatedAt: new Date('2024-01-15T14:30:00'),
  },
  {
    id: '8',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Complete safety inspection forms',
    description: 'Annual electrical safety documentation',
    priority: 'high',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-10T09:00:00'),
    updatedAt: new Date('2024-01-12T16:45:00'),
  },
  {
    id: '9',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Organize gel swatch book',
    description: 'Update with new LED color samples',
    priority: 'low',
    status: 'cancelled',
    type: 'paperwork',
    createdAt: new Date('2024-01-09T15:20:00'),
    updatedAt: new Date('2024-01-11T10:30:00'),
  },
  // Electrician type notes
  {
    id: '10',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check DMX cable run stage left',
    description: 'Intermittent signal issues on Universe 2',
    priority: 'high',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-16T07:45:00'),
    updatedAt: new Date('2024-01-16T07:45:00'),
    channelNumbers: '11-27',
    positionUnit: '1E-2E All Movers',
  },
  {
    id: '11',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install new dimmer rack cooling fan',
    description: 'Rack 3 running hot, fan replacement needed',
    priority: 'medium',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-13T10:15:00'),
    updatedAt: new Date('2024-01-15T14:20:00'),
    channelNumbers: '301-315',
    positionUnit: 'Drops & Groundrow',
  },
  {
    id: '12',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Ground fault testing on all circuits',
    description: 'Monthly safety protocol check',
    priority: 'low',
    status: 'cancelled',
    type: 'electrician',
    createdAt: new Date('2024-01-08T11:00:00'),
    updatedAt: new Date('2024-01-10T09:30:00'),
  },
  {
    id: '13',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair loose connection in patch panel',
    description: 'Circuit 28 has intermittent power loss',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-15T19:30:00'),
    updatedAt: new Date('2024-01-15T19:30:00'),
    channelNumbers: '421, 423, 425, 427',
    positionUnit: 'Box Boom L Odd Units',
  },
  // Think type notes
  {
    id: '14',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Evaluate LED retrofit for house lights',
    description: 'Cost analysis and energy savings calculation',
    priority: 'low',
    status: 'complete',
    type: 'think',
    createdAt: new Date('2024-01-07T16:00:00'),
    updatedAt: new Date('2024-01-12T13:45:00'),
  },
  {
    id: '15',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Consider wireless DMX for fly gallery',
    description: 'Cable runs problematic, research wireless options',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-14T12:30:00'),
    updatedAt: new Date('2024-01-14T12:30:00'),
  },
  {
    id: '16',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Alternative rigging for overhead specials',
    description: 'Current position blocks sightlines from balcony',
    priority: 'high',
    status: 'cancelled',
    type: 'think',
    createdAt: new Date('2024-01-11T18:15:00'),
    updatedAt: new Date('2024-01-13T15:45:00'),
  },
  {
    id: '17',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Research new haze machine options',
    description: 'Current unit too noisy for intimate scenes',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-16T14:00:00'),
    updatedAt: new Date('2024-01-16T14:00:00'),
  },
  {
    id: '18',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Plan cable management upgrade',
    description: 'Current system creating trip hazards',
    priority: 'high',
    status: 'complete',
    type: 'think',
    createdAt: new Date('2024-01-09T13:20:00'),
    updatedAt: new Date('2024-01-14T10:15:00'),
  },
  // Additional work notes for testing
  {
    id: '19',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install gobos in downstage wash',
    description: 'Add breakup gobos to Units 12-15 for texture',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T09:15:00'),
    updatedAt: new Date('2024-01-17T09:15:00'),
    lightwrightItemId: 'LW012',
    channelNumbers: '112, 113, 114, 115',
    positionUnit: 'FOH-1 Units 12-15',
    sceneryNeeds: 'Access during preset time only',
  },
  {
    id: '20',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace dimmer module in rack 3',
    description: 'Channel 305 not responding to control',
    priority: 'critical',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T11:30:00'),
    updatedAt: new Date('2024-01-17T11:30:00'),
    lightwrightItemId: 'LW305',
    channelNumbers: '305',
    sceneryNeeds: 'Power shutdown required for 30 minutes',
  },
  {
    id: '21',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus session for Act 2 ballet sequence',
    description: 'Adjust 16 specials for new choreography',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T08:00:00'),
    updatedAt: new Date('2024-01-17T14:20:00'),
    lightwrightItemId: 'LW201',
    channelNumbers: '201-209',
    positionUnit: 'Box Boom Specials 1-16',
    sceneryNeeds: 'Schedule around dancer rehearsal',
  },
  {
    id: '22',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace power connectors on SL boom',
    description: 'Two connectors cracked, need replacement',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T10:00:00'),
    updatedAt: new Date('2024-01-17T10:00:00'),
    channelNumbers: '422, 424, 426, 428',
    positionUnit: 'Box Boom L Even Units',
  },
  {
    id: '23',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Evaluate followspot arc lamp life',
    description: 'Replace before opening night',
    priority: 'high',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:45:00'),
    updatedAt: new Date('2024-01-17T10:45:00'),
    channelNumbers: '501-503',
    positionUnit: 'Spot Booth All',
  },
  {
    id: '24',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check dimmer rack phase balance',
    description: 'New loads added this week',
    priority: 'medium',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-16T12:30:00'),
    updatedAt: new Date('2024-01-17T08:10:00'),
    channelNumbers: '401-416',
    positionUnit: 'FOH Truss Frontlight',
  },
  {
    id: '25',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Add safety cables to all new fixtures',
    description: 'Verify on Friday before run-through',
    priority: 'critical',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T12:45:00'),
    updatedAt: new Date('2024-01-17T12:45:00'),
    channelNumbers: '31-47',
    positionUnit: '3E-4E All Movers',
  },
  {
    id: '26',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus balcony rail downlight',
    description: 'Cover aisles evenly',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T13:10:00'),
    updatedAt: new Date('2024-01-17T13:10:00'),
    channelNumbers: '1, 3, 5, 7',
    positionUnit: 'FOH Truss Odd Profile Movers',
  },
  {
    id: '27',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test emergency e-stop for fly system lighting',
    description: 'Ensure power cuts to designated circuits',
    priority: 'high',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-16T17:40:00'),
    updatedAt: new Date('2024-01-17T09:20:00'),
    channelNumbers: '121-136',
    positionUnit: '3E-4E Wash Movers',
  },
  {
    id: '28',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install additional circuits in booth',
    description: 'Need 4 more 20A circuits for equipment',
    priority: 'high',
    status: 'todo',
    type: 'install',
    createdAt: new Date('2024-01-17T12:00:00'),
    updatedAt: new Date('2024-01-17T12:00:00'),
    channelNumbers: '431-438',
    positionUnit: 'Box Boom R All Units',
    sceneryNeeds: 'Coordinate with house electrician',
  },
  {
    id: '29',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus specials for dream sequence',
    description: 'Tight pools for Act 1 Scene 5',
    priority: 'medium',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T19:00:00'),
    updatedAt: new Date('2024-01-16T14:30:00'),
    lightwrightItemId: 'LW155',
    channelNumbers: '131-136',
    positionUnit: 'Balcony Specials 1-8',
  },
  {
    id: '30',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test backup power systems',
    description: 'Weekly safety check of emergency lighting',
    priority: 'critical',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-16T06:00:00'),
    updatedAt: new Date('2024-01-16T07:30:00'),
    channelNumbers: '501-503',
    positionUnit: 'Emergency Systems All',
  },
  {
    id: '31',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Organize gel inventory',
    description: 'Sort and count all color filters',
    priority: 'low',
    status: 'todo',
    type: 'paperwork',
    createdAt: new Date('2024-01-17T08:30:00'),
    updatedAt: new Date('2024-01-17T08:30:00'),
  },
  {
    id: '32',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair broken color scroller',
    description: 'Unit 28 scroller jammed on R26',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T15:45:00'),
    updatedAt: new Date('2024-01-17T15:45:00'),
    lightwrightItemId: 'LW028',
    channelNumbers: '126',
    positionUnit: 'FOH-2 Unit 8',
  },
  {
    id: '33',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install haze machine upstage',
    description: 'New position for better coverage',
    priority: 'high',
    status: 'complete',
    type: 'install',
    createdAt: new Date('2024-01-15T10:15:00'),
    updatedAt: new Date('2024-01-16T16:20:00'),
    channelNumbers: '201, 203, 205, 207, 209',
    positionUnit: 'Deck Edge Footlights Odd',
    sceneryNeeds: 'Platform modification required',
  },
  {
    id: '34',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Adjust barn doors on side wash',
    description: 'Eliminate spill onto proscenium arch',
    priority: 'low',
    status: 'cancelled',
    type: 'focus',
    createdAt: new Date('2024-01-14T17:30:00'),
    updatedAt: new Date('2024-01-16T09:15:00'),
    lightwrightItemId: 'LW089',
    channelNumbers: '189-196',
    positionUnit: 'SR Boom Units 1-8',
  },
  {
    id: '35',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Evaluate wireless DMX performance',
    description: 'Occasional signal dropout in moving lights',
    priority: 'medium',
    status: 'complete',
    type: 'think',
    createdAt: new Date('2024-01-13T11:45:00'),
    updatedAt: new Date('2024-01-15T13:20:00'),
    channelNumbers: '101-116',
    positionUnit: '1E-2E Wash Movers',
  },
  {
    id: '36',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace aging followspot',
    description: 'Current unit has poor optics',
    priority: 'high',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T14:00:00'),
    updatedAt: new Date('2024-01-17T14:00:00'),
    channelNumbers: '502',
    positionUnit: 'Spot Booth Unit 2',
    sceneryNeeds: 'Booth access for installation',
  },
  {
    id: '37',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check all fixture yokes for wear',
    description: 'Preventive maintenance inspection',
    priority: 'medium',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-14T08:30:00'),
    updatedAt: new Date('2024-01-15T17:45:00'),
    channelNumbers: 'All positions',
    positionUnit: 'Theatre-wide inspection',
  },
  {
    id: '38',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Program new moving light show',
    description: 'Create chase effects for finale',
    priority: 'low',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T16:30:00'),
    updatedAt: new Date('2024-01-17T16:30:00'),
    channelNumbers: '401-412',
    positionUnit: 'Moving Light Grid',
  },
  {
    id: '39',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Update emergency contact list',
    description: 'Add new vendor and technician info',
    priority: 'low',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-16T13:00:00'),
    updatedAt: new Date('2024-01-16T15:45:00'),
  },
  {
    id: '40',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install blacklight for UV effects',
    description: 'Special effect for ghost appearances',
    priority: 'high',
    status: 'todo',
    type: 'install',
    createdAt: new Date('2024-01-17T11:15:00'),
    updatedAt: new Date('2024-01-17T11:15:00'),
    lightwrightItemId: 'LW451',
    channelNumbers: '451',
    positionUnit: 'US Right Special',
    sceneryNeeds: 'Coordinate with costume dept UV materials',
  },
  {
    id: '41',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Troubleshoot DMX termination issues',
    description: 'Occasional signal corruption on universe 2',
    priority: 'critical',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-15T20:00:00'),
    updatedAt: new Date('2024-01-16T10:30:00'),
    channelNumbers: '201-300',
    positionUnit: 'Universe 2 All Fixtures',
  },
  {
    id: '42',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Consider LED strip upgrade',
    description: 'Current strips not bright enough for cyc wash',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T09:45:00'),
    updatedAt: new Date('2024-01-17T09:45:00'),
    channelNumbers: '311-315',
    positionUnit: 'Groundrow All Units',
  },
  {
    id: '43',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus tight specials for solos',
    description: '6 spots for principal character moments',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T18:00:00'),
    updatedAt: new Date('2024-01-17T12:45:00'),
    lightwrightItemId: 'LW170',
    channelNumbers: '170-175',
    positionUnit: 'Catwalk Specials 1-6',
  },
  {
    id: '44',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace worn gel frames',
    description: 'Several frames cracked from heat',
    priority: 'medium',
    status: 'cancelled',
    type: 'work',
    createdAt: new Date('2024-01-15T12:20:00'),
    updatedAt: new Date('2024-01-16T08:30:00'),
    lightwrightItemId: 'LW045',
    positionUnit: 'Various high-wattage positions',
  },
  {
    id: '45',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install additional work lights',
    description: 'Better illumination for setup crews',
    priority: 'low',
    status: 'todo',
    type: 'install',
    createdAt: new Date('2024-01-17T07:15:00'),
    updatedAt: new Date('2024-01-17T07:15:00'),
    channelNumbers: '2, 4, 6',
    positionUnit: 'FOH Truss Even Profile Movers',
    sceneryNeeds: 'Coordinate with scenic shop',
  },
  {
    id: '46',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Document all console programming',
    description: 'Backup and archive show files',
    priority: 'critical',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-14T10:00:00'),
    updatedAt: new Date('2024-01-16T11:30:00'),
  },
  {
    id: '47',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test DMX splitter outputs',
    description: 'Verify signal levels on all ports',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T09:30:00'),
    updatedAt: new Date('2024-01-17T09:30:00'),
    channelNumbers: '11, 12, 13, 14, 15, 16, 17',
    positionUnit: '1E All Profile Movers',
  },
  {
    id: '48',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Clean lens on FOH fixtures',
    description: 'Remove dust and debris to improve output',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T11:00:00'),
    updatedAt: new Date('2024-01-17T11:00:00'),
    channelNumbers: '401, 403, 405, 407, 409, 411, 413, 415',
    positionUnit: 'FOH Truss Frontlight Odd Units',
  },
  {
    id: '49',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Audit channel patch list',
    description: 'Ensure patch matches Lightwright export',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T18:30:00'),
    updatedAt: new Date('2024-01-16T10:10:00'),
  },
  {
    id: '50',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus aisle highlights',
    description: 'Ensure safe egress lighting without spill',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T12:10:00'),
    updatedAt: new Date('2024-01-17T12:10:00'),
    channelNumbers: '21-27',
    positionUnit: '2E All Profile Movers',
  },
  {
    id: '51',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace dimmer cage filters',
    description: 'Improve dust control',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T08:40:00'),
    updatedAt: new Date('2024-01-17T08:40:00'),
    channelNumbers: '301-305',
    positionUnit: '5E Drops All Units',
  },
  {
    id: '52',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Verify breaker labeling',
    description: 'Match labels to circuits on map',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-16T09:00:00'),
    updatedAt: new Date('2024-01-16T15:30:00'),
  },
  {
    id: '53',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus downstage specials',
    description: 'Tight circles for featured performers',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T15:00:00'),
    updatedAt: new Date('2024-01-17T15:00:00'),
    channelNumbers: '202, 204, 206, 208',
    positionUnit: 'Deck Edge Footlights Even',
  },
  {
    id: '54',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair loose clamp on unit 23',
    description: 'Tighten and safety-check',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T09:50:00'),
    updatedAt: new Date('2024-01-17T09:50:00'),
    channelNumbers: '33, 35, 37',
    positionUnit: '3E Odd Profile Movers',
  },
  {
    id: '55',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace lamp in unit 77',
    description: 'End of life, flickering visible',
    priority: 'high',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T16:05:00'),
    updatedAt: new Date('2024-01-17T16:05:00'),
    channelNumbers: '41-47',
    positionUnit: '4E All Profile Movers',
  },
  {
    id: '56',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install slip mats on ladders',
    description: 'Safety improvement',
    priority: 'low',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-16T10:00:00'),
    updatedAt: new Date('2024-01-16T13:30:00'),
  },
  {
    id: '57',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Update labeling on patch panel',
    description: 'Color-coded labels for quick reference',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T14:15:00'),
    updatedAt: new Date('2024-01-16T09:00:00'),
  },
  {
    id: '58',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus mid-stage general wash',
    description: 'Even coverage across center stage',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T11:50:00'),
    updatedAt: new Date('2024-01-17T11:50:00'),
    channelNumbers: '111-116',
    positionUnit: '2E Wash Movers',
  },
  {
    id: '59',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace fan in dimmer rack 2',
    description: 'Noisy bearing reported',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T13:20:00'),
    updatedAt: new Date('2024-01-17T13:20:00'),
    channelNumbers: '402, 404, 406, 408, 410, 412, 414, 416',
    positionUnit: 'FOH Truss Frontlight Even Units',
  },
  {
    id: '60',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Clean dimmer room',
    description: 'Remove dust and debris',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:35:00'),
    updatedAt: new Date('2024-01-17T10:35:00'),
  },
  {
    id: '61',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Audit ladder inventory',
    description: 'Check condition and quantities',
    priority: 'low',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T09:50:00'),
    updatedAt: new Date('2024-01-16T12:25:00'),
  },
  {
    id: '62',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install cable troughs SR',
    description: 'Prevent trip hazards',
    priority: 'medium',
    status: 'todo',
    type: 'install',
    createdAt: new Date('2024-01-17T13:30:00'),
    updatedAt: new Date('2024-01-17T13:30:00'),
    channelNumbers: '121, 122, 123, 124, 125, 126',
    positionUnit: '3E Wash Movers',
    sceneryNeeds: 'Route cables through existing infrastructure',
  },
  {
    id: '63',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus wash lighting for dance numbers',
    description: 'Even coverage for full stage choreography',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T20:15:00'),
    updatedAt: new Date('2024-01-17T15:30:00'),
    lightwrightItemId: 'LW250',
    channelNumbers: '250-265',
    positionUnit: 'Dance Wash All Positions',
  },
  {
    id: '64',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Create equipment checkout system',
    description: 'Track tools and equipment loans',
    priority: 'low',
    status: 'cancelled',
    type: 'paperwork',
    createdAt: new Date('2024-01-14T10:45:00'),
    updatedAt: new Date('2024-01-16T16:00:00'),
  },
  {
    id: '65',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install pyrotechnic safety systems',
    description: 'Fire marshal requirements for flash effects',
    priority: 'critical',
    status: 'complete',
    type: 'install',
    createdAt: new Date('2024-01-14T12:00:00'),
    updatedAt: new Date('2024-01-15T19:30:00'),
    sceneryNeeds: 'Coordinate with fire marshal inspection',
  },
  {
    id: '66',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Troubleshoot console freezing issues',
    description: 'Intermittent lockups during complex cues',
    priority: 'high',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T16:45:00'),
    updatedAt: new Date('2024-01-17T16:45:00'),
  },
  {
    id: '67',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Plan cable storage reorganization',
    description: 'Current system inefficient for quick setup',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T12:15:00'),
    updatedAt: new Date('2024-01-17T12:15:00'),
  },
  {
    id: '68',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus key light for principal actors',
    description: 'Individual specials for star entrances',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T21:30:00'),
    updatedAt: new Date('2024-01-17T14:45:00'),
    lightwrightItemId: 'LW180',
    channelNumbers: '180-185',
    positionUnit: 'Star Specials 1-6',
  },
]
