import type { Note } from '@/types'

export const DEMO_CUE_NOTES: Note[] = [
  {
    id: 'cue-1',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Fade house lights on Overture',
    description: 'House to 50% over 5 seconds when music starts.',
    priority: 'very_high',
    status: 'todo',
    type: 'cue',
    cueNumber: '5',
    scriptPageId: 'page-1',
    sceneSongId: 'Overture',
    createdAt: new Date('2024-01-10T09:00:00'),
    updatedAt: new Date('2024-01-10T09:00:00'),
  },
  {
    id: 'cue-2',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Lighting change for opening verse',
    description: 'Transition to warmer palette on lyric',
    priority: 'medium',
    status: 'complete',
    type: 'cue',
    cueNumber: '17',
    scriptPageId: 'page-3',
    sceneSongId: 'Act 1 Scene 1',
    createdAt: new Date('2024-01-09T16:00:00'),
    updatedAt: new Date('2024-01-10T17:00:00'),
  },
  {
    id: 'cue-3',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Need dramatic lighting for death scene',
    description: 'Stronger side light and deeper shadows',
    priority: 'very_high',
    status: 'todo',
    type: 'director',
    cueNumber: '95',
    scriptPageId: 'page-11',
    sceneSongId: 'Act 1 Scene 3',
    createdAt: new Date('2024-01-12T10:00:00'),
    updatedAt: new Date('2024-01-12T10:00:00'),
  },
  {
    id: 'cue-4',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Finale blackout timing',
    description: 'Complete blackout on final chord, 2-count hold.',
    priority: 'very_high',
    status: 'complete',
    type: 'cue',
    cueNumber: '265',
    scriptPageId: 'page-38',
    sceneSongId: 'Act 2 Finale',
    createdAt: new Date('2024-01-05T12:00:00'),
    updatedAt: new Date('2024-01-09T10:00:00'),
  },
  {
    id: 'cue-5',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Dance number center special',
    description: 'Tight special on lead dancer',
    priority: 'medium',
    status: 'todo',
    type: 'choreographer',
    cueNumber: '34',
    scriptPageId: 'page-7',
    sceneSongId: 'Act 1 Scene 2',
    createdAt: new Date('2024-01-13T09:30:00'),
    updatedAt: new Date('2024-01-13T09:30:00'),
  },
  {
    id: 'cue-6',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Blue wash for dream sequence',
    description: 'Deep blue with breakup gobos',
    priority: 'medium',
    status: 'complete',
    type: 'designer',
    cueNumber: '45',
    scriptPageId: 'page-8',
    sceneSongId: 'Act 1 Scene 2',
    createdAt: new Date('2024-01-08T18:00:00'),
    updatedAt: new Date('2024-01-12T13:00:00'),
  },
  {
    id: 'cue-7',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Pre-show checklist',
    description: 'Add safety check for fly system integration',
    priority: 'medium',
    status: 'complete',
    type: 'stage_manager',
    cueNumber: '1',
    scriptPageId: 'page-1',
    sceneSongId: 'Pre-show',
    createdAt: new Date('2024-01-11T07:30:00'),
    updatedAt: new Date('2024-01-12T08:45:00'),
  },
  {
    id: 'cue-8',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Follow spot pickup for solo',
    description: 'Track SR to center stage',
    priority: 'critical',
    status: 'todo',
    type: 'spot',
    cueNumber: '67',
    scriptPageId: 'page-10',
    sceneSongId: 'Act 2 Scene 1',
    createdAt: new Date('2024-01-14T17:00:00'),
    updatedAt: new Date('2024-01-14T17:00:00'),
  },
  {
    id: 'cue-9',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Optimize memory usage in console',
    description: 'Remove unused palettes and groups',
    priority: 'very_low',
    status: 'complete',
    type: 'programmer',
    cueNumber: '25',
    scriptPageId: 'page-4',
    sceneSongId: 'Act 1 Scene 1',
    createdAt: new Date('2024-01-06T14:20:00'),
    updatedAt: new Date('2024-01-07T16:45:00'),
  },
  {
    id: 'cue-10',
    productionId: 'prod-1',
    moduleType: 'cue',
    title: 'Update lighting plot with changes',
    description: 'Reflect all modifications from tech week',
    priority: 'medium',
    status: 'todo',
    type: 'paperwork',
    cueNumber: '189',
    scriptPageId: 'page-22',
    sceneSongId: 'Act 2 Scene 2',
    createdAt: new Date('2024-01-15T16:00:00'),
    updatedAt: new Date('2024-01-15T16:00:00'),
  },
]

