import type { Note } from '@/types'

const baseDate = new Date()

export const DEMO_ELECTRICIAN_NOTES: Note[] = [
  {
    id: 'elec-note-1',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Replace burnt lamp in 1E position 3',
    description: 'HPL 575W failed during tech. Unit is dark, need replacement before dress.',
    priority: 'critical',
    status: 'todo',
    type: 'work',
    channelNumbers: '13',
    positionUnit: '1E Unit 3',
    createdAt: new Date(baseDate.getTime() - 43200000),
    updatedAt: new Date(baseDate.getTime() - 43200000),
  },
  {
    id: 'elec-note-2',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Focus FOH box boom SL',
    description: 'Refocus all units on SL box boom after scenic change moved masking.',
    priority: 'very_high',
    status: 'todo',
    type: 'focus',
    channelNumbers: '101-108',
    positionUnit: 'Box Boom SL',
    createdAt: new Date(baseDate.getTime() - 86400000),
    updatedAt: new Date(baseDate.getTime() - 86400000),
  },
  {
    id: 'elec-note-3',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Update channel hookup after repatching',
    description: 'Channels 201-215 were repatched to new dimmer rack. Update paperwork.',
    priority: 'high',
    status: 'complete',
    type: 'paperwork',
    channelNumbers: '201-215',
    createdAt: new Date(baseDate.getTime() - 259200000),
    updatedAt: new Date(baseDate.getTime() - 86400000),
  },
  {
    id: 'elec-note-4',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Check DMX termination on 2E pipe',
    description: 'Intermittent flickering on 2E movers. Suspect bad DMX terminator.',
    priority: 'critical',
    status: 'todo',
    type: 'work',
    channelNumbers: '21-30',
    positionUnit: '2E Pipe',
    createdAt: new Date(baseDate.getTime() - 21600000),
    updatedAt: new Date(baseDate.getTime() - 21600000),
  },
  {
    id: 'elec-note-5',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Run new circuit to practical lamp DS',
    description: 'Need new circuit run from dimmer room to practical table lamp position.',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    channelNumbers: '441',
    positionUnit: 'DS Practical',
    sceneryNeeds: 'Coordinate with scenic for cable path under platform',
    createdAt: new Date(baseDate.getTime() - 172800000),
    updatedAt: new Date(baseDate.getTime() - 172800000),
  },
  {
    id: 'elec-note-6',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Inventory spare lamps for movers',
    description: 'Count remaining spare lamps for VL3500 and Mac Encore. Order if below threshold.',
    priority: 'medium_low',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date(baseDate.getTime() - 345600000),
    updatedAt: new Date(baseDate.getTime() - 172800000),
  },
  {
    id: 'elec-note-7',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Safety cable check on all overhead units',
    description: 'Annual safety cable inspection on all overhead positions.',
    priority: 'very_high',
    status: 'complete',
    type: 'work',
    createdAt: new Date(baseDate.getTime() - 518400000),
    updatedAt: new Date(baseDate.getTime() - 259200000),
  },
  {
    id: 'elec-note-8',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Consider adding more SR side light',
    description: 'SR dance numbers feel flat. Think about adding a boom or pipe end position.',
    priority: 'low',
    status: 'todo',
    type: 'think',
    createdAt: new Date(baseDate.getTime() - 129600000),
    updatedAt: new Date(baseDate.getTime() - 129600000),
  },
  {
    id: 'elec-note-9',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Focus cyc lights after new cyc hung',
    description: 'New cyc was hung 6" further DS. All cyc units need refocus.',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    channelNumbers: '301-320',
    positionUnit: 'Cyc Pipe',
    createdAt: new Date(baseDate.getTime() - 64800000),
    updatedAt: new Date(baseDate.getTime() - 64800000),
  },
  {
    id: 'elec-note-10',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Repair loose connector on XBAR deck',
    description: 'Stage pin connector on deck unit 7 is loose. Retighten or replace.',
    priority: 'medium_high',
    status: 'todo',
    type: 'work',
    channelNumbers: '407',
    positionUnit: 'XBAR DECK Unit 7',
    createdAt: new Date(baseDate.getTime() - 43200000),
    updatedAt: new Date(baseDate.getTime() - 43200000),
  },
  {
    id: 'elec-note-11',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Label all new circuits in dimmer room',
    description: 'New circuits from renovation are unlabeled. Create labels and update panel schedule.',
    priority: 'medium',
    status: 'cancelled',
    type: 'paperwork',
    createdAt: new Date(baseDate.getTime() - 604800000),
    updatedAt: new Date(baseDate.getTime() - 432000000),
  },
  {
    id: 'elec-note-12',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Test backup generator transfer',
    description: 'Monthly test of generator auto-transfer switch. Schedule during dark day.',
    priority: 'very_low',
    status: 'complete',
    type: 'work',
    createdAt: new Date(baseDate.getTime() - 432000000),
    updatedAt: new Date(baseDate.getTime() - 345600000),
  },
  {
    id: 'elec-note-13',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Research LED replacement for R40 strip lights',
    description: 'Strip lights on 3E are aging. Look into LED retrofit options that maintain color quality.',
    priority: 'low',
    status: 'todo',
    type: 'think',
    channelNumbers: '31-40',
    positionUnit: '3E Strip',
    createdAt: new Date(baseDate.getTime() - 259200000),
    updatedAt: new Date(baseDate.getTime() - 259200000),
  },
  {
    id: 'elec-note-14',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Clean all FOH lenses',
    description: 'FOH units have dust buildup from construction. Clean lenses on all FOH positions.',
    priority: 'medium',
    status: 'complete',
    type: 'work',
    channelNumbers: '101-140',
    createdAt: new Date(baseDate.getTime() - 172800000),
    updatedAt: new Date(baseDate.getTime() - 86400000),
  },
  {
    id: 'elec-note-15',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Focus new floor booms for Act 2',
    description: 'Two new floor boom positions added for Act 2 dance number. Focus and circuit.',
    priority: 'very_high',
    status: 'todo',
    type: 'focus',
    channelNumbers: '451, 452, 453, 454',
    positionUnit: 'Floor Boom SL/SR',
    sceneryNeeds: 'Need clear stage, coordinate with choreographer for positions',
    createdAt: new Date(baseDate.getTime() - 32400000),
    updatedAt: new Date(baseDate.getTime() - 32400000),
  },
  {
    id: 'elec-note-16',
    productionId: 'prod-1',
    moduleType: 'electrician',
    title: 'Swap damaged gobo in mover 5',
    description: 'Gobo wheel 2, slot 3 has a cracked gobo. Replace with spare from stock.',
    priority: 'medium_high',
    status: 'cancelled',
    type: 'work',
    channelNumbers: '505',
    createdAt: new Date(baseDate.getTime() - 345600000),
    updatedAt: new Date(baseDate.getTime() - 259200000),
  },
]
