import type { Note } from '@/types'

/**
 * Pirates of Penzance Work Notes Demo Data
 *
 * All channel expressions map to actual fixtures from pirates-fixtures-data.ts
 * Position names match the Pirates fixture positions
 * Mix of realistic Pirates production tasks and generic technical tasks
 */
export const PIRATES_WORK_NOTES: Note[] = [
  // FOH TRUSS - Profile Movers (channels 1-7)
  {
    id: 'pw1',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus FOH specials for Major General entrance',
    description: 'Act 1 opening - tight spots on center stage for featured number',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-16T09:30:00'),
    updatedAt: new Date('2024-01-16T09:30:00'),
    lightwrightItemId: 'LW001',
    channelNumbers: '1-7',
    positionUnit: 'FOH TRUSS Units 21, 18, 15, 12, 9, 6, 3',
    sceneryNeeds: 'Wait for pirate ship set piece final position',
  },
  {
    id: 'pw2',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace lamp in FOH truss center unit',
    description: 'HPL flickering during tech rehearsal',
    priority: 'high',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-14T08:15:00'),
    updatedAt: new Date('2024-01-15T17:45:00'),
    lightwrightItemId: 'LW004',
    channelNumbers: '4',
    positionUnit: 'FOH TRUSS Unit 12',
  },

  // 1E - Profile Movers (channels 11-17)
  {
    id: 'pw3',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check DMX on 1E profile movers',
    description: 'Intermittent signal issues reported during run-through',
    priority: 'critical',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-16T07:45:00'),
    updatedAt: new Date('2024-01-16T07:45:00'),
    channelNumbers: '11-17',
    positionUnit: '1E All Profile Movers',
  },
  {
    id: 'pw4',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Add gobos for moonlight effect',
    description: 'Pirate ship scene - breakup pattern for romantic moment',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-15T14:20:00'),
    updatedAt: new Date('2024-01-15T14:20:00'),
    lightwrightItemId: 'LW012',
    channelNumbers: '12, 14, 16',
    positionUnit: '1E Units 11, 7, 3',
    sceneryNeeds: 'Coordinate with scenic for ship rigging height',
  },

  // 1E - Wash Movers (channels 102-106)
  {
    id: 'pw5',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Color balance for pirate chorus wash',
    description: 'Adjust CTB for warmer tone in Act 1',
    priority: 'medium',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-13T16:00:00'),
    updatedAt: new Date('2024-01-15T10:20:00'),
    lightwrightItemId: 'LW102',
    channelNumbers: '102-106',
    positionUnit: '1E Wash Movers',
  },

  // 2E - Profile Movers (channels 21-27)
  {
    id: 'pw6',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus 2E profiles for Mabel solos',
    description: 'Tight pools for "Poor Wandering One" number',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-16T11:45:00'),
    updatedAt: new Date('2024-01-16T11:45:00'),
    lightwrightItemId: 'LW023',
    channelNumbers: '22, 24, 26',
    positionUnit: '2E Units 11, 7, 3',
    sceneryNeeds: 'Schedule after choreography is set',
  },
  {
    id: 'pw7',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test 2E moving light homing',
    description: 'Units not returning to home position consistently',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-15T19:30:00'),
    updatedAt: new Date('2024-01-15T19:30:00'),
    channelNumbers: '21, 23, 25, 27',
    positionUnit: '2E Odd Units',
  },

  // 2E - Wash Movers (channels 112-116)
  {
    id: 'pw8',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Refocus general wash after deck height change',
    description: 'Platform adjusted - need even coverage across stage',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-14T10:00:00'),
    updatedAt: new Date('2024-01-16T14:30:00'),
    channelNumbers: '112-116',
    positionUnit: '2E Wash Movers All',
  },

  // 3E - Profile Movers (channels 31-37)
  {
    id: 'pw9',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Add safety cables to 3E movers',
    description: 'Verify all units have proper secondary support',
    priority: 'critical',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-10T09:00:00'),
    updatedAt: new Date('2024-01-12T16:45:00'),
    channelNumbers: '31-37',
    positionUnit: '3E All Profile Movers',
  },
  {
    id: 'pw10',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus side light for Pirate King entrance',
    description: 'Strong angular light for dramatic entrance in Act 2',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-16T13:30:00'),
    updatedAt: new Date('2024-01-16T13:30:00'),
    lightwrightItemId: 'LW032',
    channelNumbers: '32, 34, 36',
    positionUnit: '3E Even Units',
  },

  // 3E - Wash Movers (channels 122-126)
  {
    id: 'pw11',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check 3E wash mover color mixing',
    description: 'Color appears inconsistent across units',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T09:15:00'),
    updatedAt: new Date('2024-01-17T09:15:00'),
    channelNumbers: '122-126',
    positionUnit: '3E Wash Movers',
  },

  // 4E - Profile Movers (channels 41-47)
  {
    id: 'pw12',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair yoke on 4E center unit',
    description: 'Tilt mechanism sticking during movement',
    priority: 'high',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:30:00'),
    updatedAt: new Date('2024-01-17T10:30:00'),
    lightwrightItemId: 'LW044',
    channelNumbers: '44',
    positionUnit: '4E Unit 7',
  },
  {
    id: 'pw13',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus 4E backlight for dance numbers',
    description: 'All Hail the Pirate King - create depth and separation',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T18:00:00'),
    updatedAt: new Date('2024-01-16T12:45:00'),
    lightwrightItemId: 'LW041',
    channelNumbers: '41-47',
    positionUnit: '4E All Profile Movers',
  },

  // 4E - Wash Movers (channels 131-136)
  {
    id: 'pw14',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Balance 4E wash intensity',
    description: 'Even coverage needed for ensemble numbers',
    priority: 'medium',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-14T16:30:00'),
    updatedAt: new Date('2024-01-15T14:20:00'),
    channelNumbers: '131-136',
    positionUnit: '4E Wash Movers',
  },

  // DECK EDGE (channels 201-209)
  {
    id: 'pw15',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install deck edge footlight special for ship rail',
    description: 'Add uplight for pirates leaning over ship edge',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T11:15:00'),
    updatedAt: new Date('2024-01-17T11:15:00'),
    lightwrightItemId: 'LW205',
    channelNumbers: '205',
    positionUnit: 'DECK EDGE Center',
    sceneryNeeds: 'Coordinate with ship deck construction',
  },
  {
    id: 'pw16',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus deck edge for Ruth solo',
    description: 'Poor wandering one reprise - romantic footlight',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T08:00:00'),
    updatedAt: new Date('2024-01-17T14:20:00'),
    lightwrightItemId: 'LW201',
    channelNumbers: '201, 203, 207, 209',
    positionUnit: 'DECK EDGE Outer Units',
  },
  {
    id: 'pw17',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check gel saturation on deck edge units',
    description: 'High heat position - verify color integrity',
    priority: 'low',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-13T11:00:00'),
    updatedAt: new Date('2024-01-14T09:30:00'),
    channelNumbers: '201-209',
    positionUnit: 'DECK EDGE All',
  },

  // 5E - Drops (channels 302-305, 311)
  {
    id: 'pw18',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install groundrow for ocean backdrop',
    description: 'Cyc lighting for sea and sky effects',
    priority: 'high',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-12T10:15:00'),
    updatedAt: new Date('2024-01-14T16:20:00'),
    lightwrightItemId: 'LW302',
    channelNumbers: '302-305, 311',
    positionUnit: '5E Drops & Groundrow',
    sceneryNeeds: 'Install after backdrop is hung',
  },
  {
    id: 'pw19',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Color mix cyc for sunset effect',
    description: 'Act 1 finale - transition from day to twilight',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-16T15:45:00'),
    updatedAt: new Date('2024-01-16T15:45:00'),
    channelNumbers: '302, 304',
    positionUnit: '5E Drops',
  },

  // BOX BOOM L (channels 421-431)
  {
    id: 'pw20',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus box boom for Major General daughters',
    description: 'Act 1 - create pools for stage left chorus positions',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T12:00:00'),
    updatedAt: new Date('2024-01-17T12:00:00'),
    lightwrightItemId: 'LW421',
    channelNumbers: '421-427',
    positionUnit: 'BOX BOOM L Units 1-7',
  },
  {
    id: 'pw21',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace cracked connector on box boom',
    description: 'Power connector damaged - safety issue',
    priority: 'critical',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-15T20:00:00'),
    updatedAt: new Date('2024-01-16T10:30:00'),
    channelNumbers: '422, 424, 426',
    positionUnit: 'BOX BOOM L Even Units',
  },
  {
    id: 'pw22',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Adjust barn doors on box boom specials',
    description: 'Eliminate spill onto proscenium and audience',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T13:10:00'),
    updatedAt: new Date('2024-01-17T13:10:00'),
    channelNumbers: '422, 423, 424, 425, 426, 427',
    positionUnit: 'BOX BOOM L Units 2-7',
  },

  // BOX BOOM R (channels 431-439)
  {
    id: 'pw23',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install additional units on box boom right',
    description: 'Balance stage right coverage to match SL',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T09:45:00'),
    updatedAt: new Date('2024-01-17T09:45:00'),
    lightwrightItemId: 'LW432',
    channelNumbers: '432-438',
    positionUnit: 'BOX BOOM R Units 1-7',
    sceneryNeeds: 'Coordinate with set piece placement SR',
  },
  {
    id: 'pw24',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus SR box boom for Frederic solo',
    description: 'Stay I must not go - isolated special',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-14T18:30:00'),
    updatedAt: new Date('2024-01-16T11:15:00'),
    channelNumbers: '432, 434, 436',
    positionUnit: 'BOX BOOM R Even Units',
  },

  // SPOT BOOTH (channels 501-503)
  {
    id: 'pw25',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Evaluate followspot lamp life',
    description: 'Replace arc lamps before opening night',
    priority: 'critical',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:45:00'),
    updatedAt: new Date('2024-01-17T10:45:00'),
    lightwrightItemId: 'LW501',
    channelNumbers: '501-503',
    positionUnit: 'SPOT BOOTH All',
    sceneryNeeds: 'Booth access for installation',
  },
  {
    id: 'pw26',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test followspot iris mechanics',
    description: 'Ensure smooth operation for lead specials',
    priority: 'high',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-15T12:30:00'),
    updatedAt: new Date('2024-01-16T09:20:00'),
    channelNumbers: '502',
    positionUnit: 'SPOT BOOTH Unit 2',
  },

  // Mixed positions and general tasks
  {
    id: 'pw27',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Program moving light chase for Act 2 finale',
    description: 'With catlike tread - synchronized movement effects',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T16:30:00'),
    updatedAt: new Date('2024-01-17T16:30:00'),
    channelNumbers: '11, 21, 31, 41',
    positionUnit: 'All Electric Profile Movers Center',
  },
  {
    id: 'pw28',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Update hookup with circuit changes',
    description: 'Dimmer reassignments after load balancing',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-14T14:30:00'),
    updatedAt: new Date('2024-01-15T10:15:00'),
  },
  {
    id: 'pw29',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test DMX universe routing',
    description: 'Verify all fixtures responding on correct universe',
    priority: 'high',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-13T09:00:00'),
    updatedAt: new Date('2024-01-14T15:30:00'),
    positionUnit: 'All Positions',
  },
  {
    id: 'pw30',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Clean lens on all wash movers',
    description: 'Remove dust to improve output and color',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T11:00:00'),
    updatedAt: new Date('2024-01-17T11:00:00'),
    channelNumbers: '102-106, 112-116, 122-126, 132-136',
    positionUnit: 'All Wash Movers',
  },
  {
    id: 'pw31',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Organize gel swatch book',
    description: 'Update with LED color mixing equivalents',
    priority: 'low',
    status: 'cancelled',
    type: 'paperwork',
    createdAt: new Date('2024-01-09T15:20:00'),
    updatedAt: new Date('2024-01-11T10:30:00'),
  },
  {
    id: 'pw32',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus tight specials for Modern Major General',
    description: 'I am the very model... solo spotlight sequence',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T18:00:00'),
    updatedAt: new Date('2024-01-17T12:45:00'),
    lightwrightItemId: 'LW001',
    channelNumbers: '1, 3, 5, 7',
    positionUnit: 'FOH TRUSS Odd Units',
  },
  {
    id: 'pw33',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install haze machine for atmospheric effects',
    description: 'Moonlight scene and mysterious pirate appearances',
    priority: 'high',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-13T10:15:00'),
    updatedAt: new Date('2024-01-14T16:20:00'),
    sceneryNeeds: 'Position to avoid fire alarm triggers',
  },
  {
    id: 'pw34',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Troubleshoot wireless DMX dropout',
    description: 'Occasional signal loss on moving lights',
    priority: 'critical',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T08:30:00'),
    updatedAt: new Date('2024-01-17T08:30:00'),
    channelNumbers: '12-17, 22-27, 32-37, 42-47',
    positionUnit: 'All Electric Profile Movers',
  },
  {
    id: 'pw35',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Balance color temperature across electrics',
    description: 'Consistent warmth needed for period setting',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T09:45:00'),
    updatedAt: new Date('2024-01-17T09:45:00'),
    channelNumbers: '102, 112, 122, 132',
    positionUnit: 'Wash Movers 1E-4E',
  },
  {
    id: 'pw36',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Document all console programming',
    description: 'Backup show files and create cue synopsis',
    priority: 'high',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-14T10:00:00'),
    updatedAt: new Date('2024-01-16T11:30:00'),
  },
  {
    id: 'pw37',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Research LED alternatives for practical lanterns',
    description: 'Current practicals too hot for actors to handle',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T14:00:00'),
    updatedAt: new Date('2024-01-17T14:00:00'),
  },
  {
    id: 'pw38',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Check all fixture clamps and safety cables',
    description: 'Pre-opening night safety inspection',
    priority: 'critical',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-14T08:30:00'),
    updatedAt: new Date('2024-01-15T17:45:00'),
    positionUnit: 'All Fixtures Theatre-wide',
  },
  {
    id: 'pw39',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus moonlight for beach scene',
    description: 'Cool tones and texture for rocky Cornish coast',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T19:00:00'),
    updatedAt: new Date('2024-01-16T14:30:00'),
    lightwrightItemId: 'LW012',
    channelNumbers: '12-17',
    positionUnit: '1E All Units',
  },
  {
    id: 'pw40',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install blacklight for ghost pirate effect',
    description: 'UV reactive costume pieces for supernatural moment',
    priority: 'medium',
    status: 'cancelled',
    type: 'work',
    createdAt: new Date('2024-01-12T11:15:00'),
    updatedAt: new Date('2024-01-14T09:30:00'),
    sceneryNeeds: 'Coordinate with costume dept UV materials',
  },
  {
    id: 'pw41',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test emergency lighting systems',
    description: 'Weekly safety protocol check',
    priority: 'critical',
    status: 'complete',
    type: 'work',
    createdAt: new Date('2024-01-16T06:00:00'),
    updatedAt: new Date('2024-01-16T07:30:00'),
  },
  {
    id: 'pw42',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Evaluate moving light maintenance schedule',
    description: 'Plan for routine cleaning and calibration',
    priority: 'low',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T13:20:00'),
    updatedAt: new Date('2024-01-17T13:20:00'),
  },
  {
    id: 'pw43',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus sidelight for police entrance',
    description: 'Act 2 - When the foeman bares his steel',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T15:00:00'),
    updatedAt: new Date('2024-01-17T15:00:00'),
    lightwrightItemId: 'LW422',
    channelNumbers: '422-428',
    positionUnit: 'BOX BOOM L Even Units',
  },
  {
    id: 'pw44',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Repair gobo rotator unit',
    description: 'Motor jamming on cloud effect',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:20:00'),
    updatedAt: new Date('2024-01-17T10:20:00'),
    lightwrightItemId: 'LW014',
    channelNumbers: '14',
    positionUnit: '1E Unit 7',
  },
  {
    id: 'pw45',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Update emergency contact list',
    description: 'Add new vendor and technician contact info',
    priority: 'low',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-16T13:00:00'),
    updatedAt: new Date('2024-01-16T15:45:00'),
  },
  {
    id: 'pw46',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Create sunset effect for Act 1 finale',
    description: 'Gradual color shift from day to dusk',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T16:30:00'),
    updatedAt: new Date('2024-01-16T13:15:00'),
    channelNumbers: '302-305, 311',
    positionUnit: '5E All Drops',
  },
  {
    id: 'pw47',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test dimmer rack phase balance',
    description: 'New loads added - verify electrical distribution',
    priority: 'medium',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-13T12:30:00'),
    updatedAt: new Date('2024-01-14T08:10:00'),
  },
  {
    id: 'pw48',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus specials for Ruth and Frederic duet',
    description: 'Ah leave me not to pine - romantic isolation',
    priority: 'high',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T12:45:00'),
    updatedAt: new Date('2024-01-17T12:45:00'),
    lightwrightItemId: 'LW202',
    channelNumbers: '202, 204',
    positionUnit: 'DECK EDGE Units 2, 4',
  },
  {
    id: 'pw49',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Verify patch list matches console',
    description: 'Audit channel assignments after changes',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T18:30:00'),
    updatedAt: new Date('2024-01-16T10:10:00'),
  },
  {
    id: 'pw50',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Consider wireless DMX for spot booth',
    description: 'Cable run problematic - research alternatives',
    priority: 'low',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T11:30:00'),
    updatedAt: new Date('2024-01-17T11:30:00'),
  },
  {
    id: 'pw51',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Adjust timing on mover presets',
    description: 'Faster transitions needed for comedy beats',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T14:20:00'),
    updatedAt: new Date('2024-01-17T14:20:00'),
    channelNumbers: '21-27',
    positionUnit: '2E All Profile Movers',
  },
  {
    id: 'pw52',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Replace worn gel frames on high-temp units',
    description: 'Heat damage visible on FOH positions',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T09:00:00'),
    updatedAt: new Date('2024-01-17T09:00:00'),
    channelNumbers: '2, 4, 6',
    positionUnit: 'FOH TRUSS Even Units',
  },
  {
    id: 'pw53',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Verify breaker labeling',
    description: 'Match panel labels to circuit documentation',
    priority: 'medium',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-16T09:00:00'),
    updatedAt: new Date('2024-01-16T15:30:00'),
  },
  {
    id: 'pw54',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus backlight for silhouette effects',
    description: 'Pirate ship silhouettes against moonlit sky',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T20:15:00'),
    updatedAt: new Date('2024-01-17T15:30:00'),
    lightwrightItemId: 'LW132',
    channelNumbers: '132, 134, 136',
    positionUnit: '4E Wash Movers',
  },
  {
    id: 'pw55',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install cable troughs stage right',
    description: 'Prevent trip hazards during scene changes',
    priority: 'medium',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T13:30:00'),
    updatedAt: new Date('2024-01-17T13:30:00'),
    sceneryNeeds: 'Route cables through existing infrastructure',
  },
  {
    id: 'pw56',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Balance wash coverage for ensemble dance',
    description: 'With catlike tread - full stage choreography',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T14:45:00'),
    updatedAt: new Date('2024-01-16T12:30:00'),
    channelNumbers: '102, 112, 122, 132',
    positionUnit: 'All Electrics Wash',
  },
  {
    id: 'pw57',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Audit ladder and lift inventory',
    description: 'Check condition and safety equipment',
    priority: 'low',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-15T09:50:00'),
    updatedAt: new Date('2024-01-16T12:25:00'),
  },
  {
    id: 'pw58',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Program storm effect for shipwreck scene',
    description: 'Flicker and flash effects synchronized with sound',
    priority: 'medium',
    status: 'todo',
    type: 'focus',
    createdAt: new Date('2024-01-17T16:00:00'),
    updatedAt: new Date('2024-01-17T16:00:00'),
    channelNumbers: '1-7, 11-17',
    positionUnit: 'FOH TRUSS & 1E Movers',
  },
  {
    id: 'pw59',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Clean dimmer room and racks',
    description: 'Remove dust for better cooling efficiency',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T10:35:00'),
    updatedAt: new Date('2024-01-17T10:35:00'),
  },
  {
    id: 'pw60',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test console backup system',
    description: 'Verify automatic save and redundancy',
    priority: 'critical',
    status: 'complete',
    type: 'electrician',
    createdAt: new Date('2024-01-14T11:00:00'),
    updatedAt: new Date('2024-01-14T16:45:00'),
  },
  {
    id: 'pw61',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Focus star specials for lead trio',
    description: 'Mabel, Frederic, Pirate King featured moments',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-16T21:30:00'),
    updatedAt: new Date('2024-01-17T14:45:00'),
    lightwrightItemId: 'LW003',
    channelNumbers: '3, 5, 13, 15',
    positionUnit: 'FOH TRUSS & 1E Center',
  },
  {
    id: 'pw62',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Research LED strip upgrade for cyc',
    description: 'Current strips insufficient for brightness needs',
    priority: 'medium',
    status: 'todo',
    type: 'think',
    createdAt: new Date('2024-01-17T12:15:00'),
    updatedAt: new Date('2024-01-17T12:15:00'),
  },
  {
    id: 'pw63',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Install work lights for crew preset',
    description: 'Better illumination for scene change crew',
    priority: 'low',
    status: 'todo',
    type: 'work',
    createdAt: new Date('2024-01-17T07:15:00'),
    updatedAt: new Date('2024-01-17T07:15:00'),
    sceneryNeeds: 'Coordinate with stage management positions',
  },
  {
    id: 'pw64',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Complete safety inspection forms',
    description: 'Annual electrical safety documentation',
    priority: 'critical',
    status: 'complete',
    type: 'paperwork',
    createdAt: new Date('2024-01-10T09:00:00'),
    updatedAt: new Date('2024-01-12T16:45:00'),
  },
  {
    id: 'pw65',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Test moving light pan/tilt limits',
    description: 'Verify no collision with masking or set pieces',
    priority: 'high',
    status: 'complete',
    type: 'focus',
    createdAt: new Date('2024-01-15T13:30:00'),
    updatedAt: new Date('2024-01-16T10:45:00'),
    channelNumbers: '31-37',
    positionUnit: '3E All Profile Movers',
  },
  {
    id: 'pw66',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Troubleshoot console network connectivity',
    description: 'Remote access intermittently dropping',
    priority: 'medium',
    status: 'todo',
    type: 'electrician',
    createdAt: new Date('2024-01-17T16:45:00'),
    updatedAt: new Date('2024-01-17T16:45:00'),
  },
  {
    id: 'pw67',
    productionId: 'prod-1',
    moduleType: 'work',
    title: 'Create lighting plot for understudy rehearsal',
    description: 'Simplified version for practice sessions',
    priority: 'low',
    status: 'cancelled',
    type: 'paperwork',
    createdAt: new Date('2024-01-14T10:45:00'),
    updatedAt: new Date('2024-01-16T16:00:00'),
  },
]
