import type { Note } from '@/types'

export const DEMO_PRODUCTION_NOTES: Note[] = [
  {
    id: 'prod-1',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Upstage platform at 4 feet blocks key light from FOH',
    priority: 'very_high',
    status: 'todo',
    type: 'scenic',
    createdAt: new Date('2024-01-16T10:30:00'),
    updatedAt: new Date('2024-01-16T10:30:00'),
  },
  {
    id: 'prod-2',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'New silk fabric responds well to blue wash',
    priority: 'medium',
    status: 'complete',
    type: 'costumes',
    createdAt: new Date('2024-01-13T16:30:00'),
    updatedAt: new Date('2024-01-15T14:20:00'),
  },
  {
    id: 'prod-3',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Need 6 more circuits for expanded design',
    priority: 'very_high',
    status: 'todo',
    type: 'lighting',
    createdAt: new Date('2024-01-15T18:30:00'),
    updatedAt: new Date('2024-01-15T18:30:00'),
  },
  {
    id: 'prod-4',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Stage lanterns too bright, need inline dimmers',
    priority: 'medium',
    status: 'todo',
    type: 'props',
    createdAt: new Date('2024-01-14T12:15:00'),
    updatedAt: new Date('2024-01-14T12:15:00'),
  },
  {
    id: 'prod-5',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Sync lighting blackouts with sound effects timing',
    priority: 'very_high',
    status: 'complete',
    type: 'sound',
    createdAt: new Date('2024-01-13T14:00:00'),
    updatedAt: new Date('2024-01-16T11:30:00'),
  },
  {
    id: 'prod-6',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Need to flag or adjust FOH positions to prevent spill',
    priority: 'very_high',
    status: 'todo',
    type: 'video',
    createdAt: new Date('2024-01-16T13:20:00'),
    updatedAt: new Date('2024-01-16T13:20:00'),
  },
  {
    id: 'prod-7',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Updated emergency lighting and evacuation procedures',
    priority: 'very_high',
    status: 'complete',
    type: 'stage_management',
    createdAt: new Date('2024-01-11T08:30:00'),
    updatedAt: new Date('2024-01-13T17:15:00'),
  },
  {
    id: 'prod-8',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Flying effects would interfere with lighting grid',
    priority: 'very_high',
    status: 'complete',
    type: 'directing',
    createdAt: new Date('2024-01-14T10:00:00'),
    updatedAt: new Date('2024-01-15T15:30:00'),
  },
  {
    id: 'prod-9',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'New triangle formation needs 3 specials not 2',
    priority: 'medium',
    status: 'todo',
    type: 'choreography',
    createdAt: new Date('2024-01-15T20:00:00'),
    updatedAt: new Date('2024-01-15T20:00:00'),
  },
  {
    id: 'prod-10',
    productionId: 'prod-1',
    moduleType: 'production',
    description: 'Additional LED fixtures pushed costs over by 8%',
    priority: 'medium',
    status: 'todo',
    type: 'production_management',
    createdAt: new Date('2024-01-16T14:30:00'),
    updatedAt: new Date('2024-01-16T14:30:00'),
  },
]

